# workflow:
#   name: App workflow

# stages:
#     - build
#     - test
#     - deploy

# build-job:
#     stage: build
#     script:
#         - echo "Hello, $GITLAB_USER_LOGIN!"

# test-job1:
#     stage: test
#     script:
#         - echo "Application testing 1 is completed."

# test-job2:
#     stage: test
#     script:
#         - echo "Application testing 2 is completed."

# deploy-job:
#     stage: deploy
#     script:
#         - echo "Application is deployed from $CI_COMMIT_BRANCH branch."
